export const LMS_BOOTSTRAP_REQUEST = 'lms/LMS_BOOTSTRAP_REQUEST';
export const LMS_BOOTSTRAP_SUCCESS = 'lms/LMS_BOOTSTRAP_SUCCESS';
export const LMS_BOOTSTRAP_FAILURE = 'lms/LMS_BOOTSTRAP_FAILURE';

export const ENROLLMENT_SUBMIT_REQUEST = 'lms/ENROLLMENT_SUBMIT_REQUEST';
export const ENROLLMENT_SUBMIT_SUCCESS = 'lms/ENROLLMENT_SUBMIT_SUCCESS';

export const QUIZ_SIMULATION_REQUEST = 'lms/QUIZ_SIMULATION_REQUEST';
export const QUIZ_SIMULATION_SUCCESS = 'lms/QUIZ_SIMULATION_SUCCESS';
export const QUIZ_QUESTION_SET_REQUEST = 'lms/QUIZ_QUESTION_SET_REQUEST';
export const QUIZ_QUESTION_SET_SUCCESS = 'lms/QUIZ_QUESTION_SET_SUCCESS';

export const ADMIN_TOGGLE_MODULE_VISIBILITY_REQUEST =
  'lms/ADMIN_TOGGLE_MODULE_VISIBILITY_REQUEST';
export const ADMIN_TOGGLE_MODULE_VISIBILITY_SUCCESS =
  'lms/ADMIN_TOGGLE_MODULE_VISIBILITY_SUCCESS';

export const ADMIN_UPLOAD_MODULE_REQUEST = 'lms/ADMIN_UPLOAD_MODULE_REQUEST';
export const ADMIN_UPLOAD_MODULE_SUCCESS = 'lms/ADMIN_UPLOAD_MODULE_SUCCESS';

export const ADMIN_UPDATE_ENROLLMENT_STATUS_REQUEST =
  'lms/ADMIN_UPDATE_ENROLLMENT_STATUS_REQUEST';
export const ADMIN_UPDATE_ENROLLMENT_STATUS_SUCCESS =
  'lms/ADMIN_UPDATE_ENROLLMENT_STATUS_SUCCESS';
