export const styles = {
  card: {
    width: 1,
    height: '100%',
    borderRadius: 2.5,
    border: '1px solid',
    borderColor: 'divider',
    boxShadow: 'none',
    transition: (theme) => theme.transitions.create(['box-shadow', 'border-color'], { duration: 180 }),
    '&:hover': {
      borderColor: 'action.hover',
      boxShadow: (theme) => theme.shadows[2],
    },
  },
  previewClickable: {
    cursor: 'pointer',
    borderRadius: 1,
    m: -0.5,
    p: 0.5,
    outlineOffset: 2,
    transition: (theme) => theme.transitions.create(['box-shadow'], { duration: 180 }),
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'primary.main',
    },
  },
  cardContent: { p: 1.5 },
  categoryCaptionOuter: { opacity: 0.84 },
  badgeChip: { height: 24, '& .MuiChip-label': { px: 1, fontWeight: 700 } },
  /** Banner overlays — dark glass so label / chip / icon stay readable on any photo. */
  bannerCategoryLabel: {
    display: 'inline-block',
    alignSelf: 'flex-start',
    maxWidth: 'min(72%, 220px)',
    px: 1,
    py: 0.45,
    borderRadius: 1,
    fontWeight: 700,
    lineHeight: 1.35,
    letterSpacing: '0.02em',
    color: 'common.white',
    bgcolor: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid rgba(255,255,255,0.18)',
    boxShadow: '0 1px 4px rgba(0,0,0,0.45)',
    opacity: 1,
  },
  bannerBadgeChip: {
    height: 26,
    maxWidth: 'min(52%, 200px)',
    flexShrink: 0,
    color: '#ffffff',
    bgcolor: 'rgba(15, 23, 42, 0.9) !important',
    border: '1px solid rgba(255,255,255,0.18)',
    boxShadow: '0 1px 4px rgba(0,0,0,0.4)',
    '& .MuiChip-label, & .MuiTypography-root': {
      px: 1,
      fontWeight: 700,
      color: '#ffffff !important',
      WebkitTextFillColor: '#ffffff',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
  },
  artIconStack: {
    mt: 3.5,
    width: 56,
    height: 56,
    borderRadius: 2,
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(255,255,255,0.14)',
    backdropFilter: 'blur(8px)',
  },
  bannerIconBox: {
    mt: 3.5,
    width: 56,
    height: 56,
    borderRadius: 2,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    color: 'common.white',
    bgcolor: 'rgba(15, 23, 42, 0.88)',
    border: '1px solid rgba(255,255,255,0.28)',
    boxShadow: '0 2px 12px rgba(0,0,0,0.5)',
    backdropFilter: 'blur(10px)',
  },
  categoryCaption: { color: 'text.secondary' },
  title: { minHeight: 58, lineHeight: 1.3 },
  courseMetaIcon: { color: 'text.secondary' },
  courseMetaText: { color: 'text.secondary' },
  ratingCaption: { color: 'text.secondary' },
  statusCaption: { color: 'text.secondary' },
  statusChip: { width: 'fit-content', textTransform: 'capitalize' },
  updatedCaption: { color: 'text.secondary' },
  updatedValue: { fontWeight: 600 },
  menuTrigger: {
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: 1,
  },
  menuPaper: {
    mt: 0.75,
    minWidth: { xs: 'min(calc(100vw - 24px), 320px)', sm: 220 },
    maxWidth: 'min(calc(100vw - 16px), 360px)',
    maxHeight: 'min(70dvh, 420px)',
    boxShadow: (theme) => theme.shadows[8],
  },
  menuItem: {
    py: 1,
    minHeight: { xs: 48, sm: 44 },
    borderRadius: 1,
    mx: 0.5,
    '& .MuiListItemIcon-root': { color: 'text.secondary' },
    '&:hover': {
      bgcolor: 'action.hover',
      '& .MuiListItemIcon-root': { color: 'primary.main' },
      '& .MuiTypography-root': { color: 'primary.main' },
    },
  },
};
