export const styles = {
  root: {
    px: 1.75,
    pb: 1.75,
    pt: 1.5,
    gap: 1.25,
  },
  addIconWrap: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    bgcolor: 'primary.main',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addIcon: { color: 'common.white' },
  addButton: {
    minHeight: 36,
    px: 1,
    py: 0.5,
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.25,
    textTransform: 'none',
    color: 'primary.main',
    '& .MuiButton-startIcon': { mr: 0.625, ml: -0.125 },
  },
  searchIcon: { color: 'text.disabled' },
  searchButton: (theme) => ({
    minHeight: 36,
    px: 1.75,
    py: 0.5,
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.25,
    textTransform: 'none',
    borderRadius: 1.5,
    color: 'text.secondary',
    border: '1px solid',
    borderColor: theme.palette.grey[300],
    bgcolor: theme.palette.grey[100],
    boxShadow: 'none',
    '&:hover': {
      borderColor: theme.palette.grey[400],
      bgcolor: theme.palette.grey[200],
      boxShadow: 'none',
    },
    '& .MuiButton-startIcon': { mr: 0.625, ml: -0.125 },
  }),
};
